// DO NOT EDIT: This file is generated by var_gen.go

package lib

const (
	varApplication       = "BELUGA_APPLICATION"
	varDeployDockerHost  = "BELUGA_DEPLOY_DOCKER_HOST"
	varDockerComposeFile = "BELUGA_DOCKER_COMPOSE_FILE"
	varDockerContext     = "BELUGA_DOCKER_CONTEXT"
	varDockerfile        = "BELUGA_DOCKERFILE"
	varDomain            = "BELUGA_DOMAIN"
	varEnvironment       = "BELUGA_ENVIRONMENT"
	varGitDefaultBranch  = "BELUGA_GIT_DEFAULT_BRANCH"
	varImage             = "BELUGA_IMAGE"
	varRegistry          = "BELUGA_REGISTRY"
	varRegistryPassword  = "BELUGA_REGISTRY_PASSWORD"
	varRegistryUsername  = "BELUGA_REGISTRY_USERNAME"
	varVariant           = "BELUGA_VARIANT"
	varVersion           = "BELUGA_VERSION"
)

var knownVarNames = []string{
	varApplication,
	varDeployDockerHost,
	varDockerComposeFile,
	varDockerContext,
	varDockerfile,
	varDomain,
	varEnvironment,
	varGitDefaultBranch,
	varImage,
	varRegistry,
	varRegistryPassword,
	varRegistryUsername,
	varVariant,
	varVersion,
}

// If provided, name of the (sub)application to compile
func (e Environment) Application() string {
	return e[varApplication]
}

// DOCKER_HOST environment variable to use while deploying
func (e Environment) DeployDockerHost() string {
	return e[varDeployDockerHost]
}

// Path to a docker-compose.yaml file to deploy
func (e Environment) DockerComposeFile() string {
	return e[varDockerComposeFile]
}

// Context of the docker build, defaults to root of the project
func (e Environment) DockerContext() string {
	return e[varDockerContext]
}

// Dockerfile to use in docker build, defaults `Dockerfile` in the context
// directory (like docker does)
func (e Environment) Dockerfile() string {
	return e[varDockerfile]
}

// Domain name to deploy the stack to. This will be passed to the environment
// when doing the docker deploy, so the compose file can reference this
// appropriately.
func (e Environment) Domain() string {
	return e[varDomain]
}

// Environment to deploy to. "review", "staging", "production" are defaults,
// but any string may be used.
func (e Environment) Environment() string {
	return e[varEnvironment]
}

// Target branch for PRs/MRs. Defaults to master.
func (e Environment) GitDefaultBranch() string {
	return e[varGitDefaultBranch]
}

// Docker image path to push to after build
func (e Environment) Image() string {
	return e[varImage]
}

// Docker registry to log into before pushing
func (e Environment) Registry() string {
	return e[varRegistry]
}

// Password to use to log into Docker registry
func (e Environment) RegistryPassword() string {
	return e[varRegistryPassword]
}

// Username to use to log into Docker registry
func (e Environment) RegistryUsername() string {
	return e[varRegistryUsername]
}

// Variant build of the application. This is helpful for situations where one
// application is deployed with different builds for different settings.
func (e Environment) Variant() string {
	return e[varVariant]
}

// Version of the application being built/deployed
func (e Environment) Version() string {
	return e[varVersion]
}
