development:
  dialect: "sqlite3"
  database: ../belugad_development.sqlite

test:
  dialect: "sqlite3"
  database: ../belugad_test.sqlite

production:
  dialect: "sqlite3"
  database: ./belugad_production.sqlite
