development:
  dialect: "sqlite3"
  database: ../belugad_development.sqlite

test:
  dialect: "sqlite3"
  database: ../belugad_test.sqlite

production:
  dialect: "sqlite3"
  database: {{env "BELUGAD_DATA"}}/belugad_production.sqlite
